name: kreaStream Derleyici

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_run:
    workflows: ["Domain Değişiklik Kontrolü"]
    types:
      - completed
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - "**/*.md"
      - "**/*.yml"
      - "**/*.jpg"
      - "**/*.png"
      - "**/*.py"

jobs:
  kreaStreamDerleyici:
    runs-on: ubuntu-latest
    steps:
      - name: "'src' Depo Kontrolü"
        uses: actions/checkout@v4.2.2
        with:
          path: "src"

      - name: "'build' Depo Kontrolü"
        uses: actions/checkout@v4.2.2
        with:
          ref: "builds"
          path: "builds"

      #- name: Eski Derlemeleri Temizle
        #run: rm $GITHUB_WORKSPACE/builds/*.cs3 || true
        #run: find $GITHUB_WORKSPACE/builds -name '*.cs3' -delete

      - name: JDK 17 Ayarla
        uses: actions/setup-java@v4.6.0
        with:
          distribution: adopt
          java-version: 17

      - name: Android SDK Ayarla
        uses: android-actions/setup-android@v3.2.2

      - name: Eklentileri Derle
        run: |
          cd $GITHUB_WORKSPACE/src
          chmod +x gradlew
          ./gradlew make makePluginsJson
          cp **/build/*.cs3 $GITHUB_WORKSPACE/builds
          cp build/plugins.json $GITHUB_WORKSPACE/builds

      #- name: jq Araçlarını Kur (GolgeTV ve AnimeciX eklemeleri için)
        #run: sudo apt-get update && sudo apt-get install -y jq

      - name: HDFilmCehennemi Eklentisini plugins.json'a Elle Ekle
        run: |
          cd $GITHUB_WORKSPACE/builds
          if ! jq -e '.[] | select(.internalName == "HDFilmCehennemi")' plugins.json > /dev/null; then
            cat plugins.json | jq '. += [{
              "repositoryUrl": "https://github.com/kreadir/kreastream",
              "apiVersion": 1,
              "status": 1,
              "language": "tr",
              "authors": ["kreaStream"],
              "tvTypes": ["Tv","Movie"],
              "version": 3,
              "internalName": "HDFilmCehennemi",
              "description": "Türkiye'\''nin en hızlı hd film izleme sitesi",
              "url": "https://raw.githubusercontent.com/Kraptor123/cs-kraptor/builds/HDFilmCehennemi.cs3",
              "name": "HDFilmCehennemi",
              "iconUrl": "https://www.google.com/s2/favicons?domain=hdfilmcehennemi.com&sz=%size%"
            }]' > plugins-new.json && mv plugins-new.json plugins.json
          else
            echo "HDFilmCehennemi zaten plugins.json'da mevcut, eklenmedi."
          fi

      - name: Yerli Diziler Eklentisini plugins.json'a Elle Ekle
        run: |
          cd $GITHUB_WORKSPACE/builds
          if ! jq -e '.[] | select(.internalName == "YerelDiziler")' plugins.json > /dev/null; then
            jq '. += [{
              "repositoryUrl": "https://github.com/kerimmkirac/cs-kerim",
              "apiVersion": 3,
              "status": 1,
              "language": "tr",
              "authors": ["kerimmkirac"],
              "tvTypes": ["Tv"],
              "version": 2,
              "internalName": "YerelDiziler",
              "description": "YerelDiziler için CloudStream eklentisi",
              "url": "https://github.com/kerimmkirac/cs-kerim/raw/refs/heads/builds/YerelDiziler.cs3",
              "name": "YerelDiziler",
              "iconUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Flag_of_Turkey.svg/960px-Flag_of_Turkey.svg.png"
            }]' plugins.json > plugins-new.json && mv plugins-new.json plugins.json
          else
            echo "YerelDiziler zaten plugins.json'da mevcut, eklenmedi."
          fi

      - name: Puhu Eklentisini plugins.json'a Elle Ekle
        run: |
          cd $GITHUB_WORKSPACE/builds
          if ! jq -e '.[] | select(.internalName == "Puhu")' plugins.json > /dev/null; then
            jq '. += [{
              "repositoryUrl": "https://github.com/kerimmkirac/cs-kerim",
              "apiVersion": 1,
              "status": 1,
              "language": "tr",
              "authors": ["kerimmkirac"],
              "tvTypes": ["TvSeries"],
              "version": 1,
              "internalName": "Puhu",
              "description": "Puhu için CloudStream eklentisi",
              "url": "https://github.com/kerimmkirac/cs-kerim/raw/refs/heads/builds/Puhu.cs3",
              "name": "Puhu",
              "iconUrl": "https://is1-ssl.mzstatic.com/image/thumb/Purple211/v4/35/c3/b7/35c3b7b0-4a84-cceb-d3e2-349e19712b07/AppIcon-0-0-1x_U007epad-0-1-0-85-220.png/512x512bb.jpg"
            }]' plugins.json > plugins-new.json && mv plugins-new.json plugins.json
          else
            echo "Puhu zaten plugins.json'da mevcut, eklenmedi."
          fi

      - name: JetFilmizle Eklentisini plugins.json'a Elle Ekle
        run: |
          cd $GITHUB_WORKSPACE/builds
          if ! jq -e '.[] | select(.internalName == "JetFilmizle")' plugins.json > /dev/null; then
            jq '. += [{
              "iconUrl": "https://t2.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://jetfilmizle.de&size=128",
              "apiVersion": 1,
              "repositoryUrl": "https://github.com/Kraptor123/cs-kraptor",
              "fileSize": 22713,
              "status": 1,
              "language": "tr",
              "authors": [
              "kraptor",
              "keyiflerolsun"
              ],
              "tvTypes": [
                "Movie"
              ],
              "version": 35,
              "internalName": "JetFilmizle",
              "description": "Binlerce Film İzleme Seçeneğiyle En İyi Film İzleme Sitesi",
              "url": "https://raw.githubusercontent.com/Kraptor123/cs-kraptor/builds/JetFilmizle.cs3",
              "name": "JetFilmizle"
            }]' plugins.json > plugins-new.json && mv plugins-new.json plugins.json
          else
            echo "Puhu zaten plugins.json'da mevcut, eklenmedi."
          fi

      - name: Derlemeleri Yükle
        run: |
          cd $GITHUB_WORKSPACE/builds
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m "$GITHUB_SHA 'nın Derlenmesi" || exit 0   # eğer commit edilecek bir şey yoksa hata verme
          git push --force
